### ISSUE TITLE
Should we accept a consent request with no purpose?

### ISSUE THREAD

**Issue by mrastrom** [MagnumOpuses/af-connect-module#40]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ixuz** [comment]
I believe every data request should have a declared purpose.

The current af-connect-module does not enforce this behavior, it merely prints a warning text into console, see:
https://github.com/MagnumOpuses/af-connect-module/blob/92998571d4aecd1da992971e2022961a22a9e425/lib/connect-module.js#L141

**Comment by ixuz** [comment]
@mrastrom I've adressed this issue now in PR commit: https://github.com/MagnumOpuses/af-connect-module/pull/39/commits/a90317122f34e2da8746014d4faddb80470c2074
